# Conexiune la RabbitMQ (portul mapat de Docker pe host)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# Interval trimitere (ms)
simulator.interval-ms=1000

# UUID-ul device-ului simulat (schimb? cu unul real din DB, dac? vrei)
simulator.device-id=7bf0cc46-ec7c-4176-894b-6289e651b065
