spring.application.name=realtime-support-service


server.port=8085
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.dynamic=true
spring.rabbitmq.listener.simple.missing-queues-fatal=false

openai.api.key=${OPENAI_API_KEY:}
openai.model=gpt-5-mini



